#GET http://localhost:3001/api/persons/1

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Jim",
  "number": 123456789
}

###
GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/67d8826605bffc69f9c5335d
#DELETE http://localhost:3001/api/persons/5

###ONLINE REQUEST!!!

GET fullstackopennode-production-914c.up.railway.app/api/persons